export const analysisSchema = Object.freeze({
  $id: "https://llm-wiki.local/schemas/analysis-envelope-v1.json",
  type: "object",
  required: [
    "schemaVersion", "taskId", "batchId", "sourceRefs", "entities", "concepts",
    "claims", "relations", "contradictions", "candidatePages", "reviewItems",
    "batchSummary", "unresolvedQuestions",
  ],
  properties: {
    schemaVersion: { const: 1 },
    taskId: { type: "string" },
    batchId: { type: "string" },
    sourceRefs: {
      type: "array",
      description: "Catalog of every unique complete SourceRef used by this envelope. With sourceRefMode=batch-evidence-index, copy the numeric scaffold catalog and use evidence_catalog indexes in nested candidates; Core persists resolved complete references.",
      items: {
        oneOf: [
          { type: "integer", minimum: 0 },
          { $ref: "#/$defs/sourceRef" },
        ],
      },
      minItems: 1,
      maxItems: 500,
    },
    sourceRefMode: { enum: ["batch-evidence-index"], description: "Optional fast path for server-generated evidence indexes returned by get_batch." },
    entities: {
      type: "array",
      description: "When a progressive Domain Schema is active, every entity must include schemaClassification with its Domain, ABE, BE, and JSON Pointer.",
      items: { $ref: "#/$defs/groundedCandidate" },
      maxItems: 500,
    },
    concepts: { type: "array", items: { $ref: "#/$defs/groundedCandidate" }, maxItems: 500 },
    claims: { type: "array", items: { $ref: "#/$defs/groundedCandidate" }, maxItems: 1000 },
    relations: {
      type: "array",
      description: "Source-grounded relationships between extracted candidates. Keep the evidence-facing statement in content and put normalized structure in sourceEntityLocalId, predicate, and targetEntityLocalId.",
      items: { $ref: "#/$defs/groundedCandidate" },
      maxItems: 1000,
    },
    contradictions: { type: "array", items: { $ref: "#/$defs/groundedCandidate" }, maxItems: 500 },
    candidatePages: { type: "array", items: { $ref: "#/$defs/groundedCandidate" }, maxItems: 500 },
    reviewItems: { type: "array", items: { $ref: "#/$defs/reviewItem" }, maxItems: 500 },
    batchSummary: { type: "string", maxLength: 20000 },
    unresolvedQuestions: { type: "array", items: { type: "string", maxLength: 2000 }, maxItems: 200 },
  },
  additionalProperties: false,
  $defs: {
    sourceRef: {
      type: "object",
      required: ["sourceId", "chunkId"],
      properties: {
        sourceId: { type: "string" },
        chunkId: { type: "string" },
        quote: { type: "string", maxLength: 1000, description: "Short verbatim evidence. Core validates exact source provenance separately from field-aware claim and relation support." },
        locator: { type: "object" },
      },
      additionalProperties: false,
    },
    sourceRefList: {
      type: "array",
      description: "One or more zero-based indexes into the top-level sourceRefs catalog. Complete SourceRef objects remain accepted for backward compatibility. The Core resolves indexes before validation and persistence.",
      items: {
        oneOf: [
          { type: "integer", minimum: 0 },
          { $ref: "#/$defs/sourceRef" },
        ],
      },
      minItems: 1,
      maxItems: 500,
    },
    groundedCandidate: {
      type: "object",
      required: ["sourceRefs"],
      properties: {
        localId: { type: "string" },
        local_id: { type: "string" },
        name: { type: "string" },
        title: { type: "string" },
        text: { type: "string" },
        content: { type: "string" },
        supportType: { enum: ["direct", "normalized", "inferred"], description: "direct preserves a source-supported statement; normalized uses deterministic lexical or predicate normalization; inferred items must be moved to reviewItems or unresolvedQuestions before commit." },
        confidence: { type: "number", minimum: 0, maximum: 1 },
        sourceEntityLocalId: { type: "string", description: "localId of the source entity in a relation." },
        predicate: { type: "string", description: "Canonical relation predicate. Core validates it independently so endpoint overlap cannot hide an unsupported predicate." },
        targetEntityLocalId: { type: "string", description: "localId of the target entity in a relation." },
        subject: { type: "string", description: "Optional evidence-facing source endpoint name for legacy or cross-batch relations." },
        object: { type: "string", description: "Optional evidence-facing target endpoint name for legacy or cross-batch relations." },
        properties: { type: "object", description: "Source-grounded structured properties when useful." },
        schemaClassification: {
          type: "object",
          description: "Progressive directory Schema classification. Copy Domain/ABE from the level=abe classification_scaffold and select BE from be_pointer_hints; input JSON field names are unrestricted.",
          properties: {
            status: { enum: ["classified", "unresolved"] },
            confidence: { type: "number", minimum: 0, maximum: 1 },
            domain: { type: "object" },
            abe: { type: "object" },
            be: { type: "object" },
            snapshotHash: { type: "string" },
          },
          additionalProperties: true,
        },
        sourceRefs: { $ref: "#/$defs/sourceRefList" },
      },
      additionalProperties: true,
    },
    reviewItem: {
      type: "object",
      required: ["content", "sourceRefs"],
      properties: {
        localId: { type: "string" },
        local_id: { type: "string" },
        content: { type: "string", minLength: 1, maxLength: 10000 },
        confidence: { type: "number", minimum: 0, maximum: 1 },
        sourceRefs: { $ref: "#/$defs/sourceRefList" },
      },
      additionalProperties: true,
    },
  },
})

export const pagePatchSchema = Object.freeze({
  $id: "https://llm-wiki.local/schemas/page-patch-v2.json",
  type: "object",
  required: ["patchId", "path", "operation", "title", "pageKind", "sourceRefs", "rationale"],
  properties: {
    patchId: { type: "string", minLength: 1, maxLength: 200 },
    path: { type: "string", pattern: "^wiki/(sources|entities|concepts|topics|comparisons|queries|synthesis|findings|methodology|thesis|meetings|decisions|projects|stakeholders|goals|habits|reflections|chapters|characters|themes|plot-threads|journal)/.+\\.md$" },
    operation: {
      enum: ["create", "replace", "merge"],
      description: "create writes a new complete page; replace rewrites a complete existing page that was fully visible to the Drafter; merge applies bounded sectionChanges to a truncated existing page without appending a second body.",
    },
    expectedFileHash: { type: "string", pattern: "^[0-9a-f]{64}$", description: "Required for replace and merge when the path already exists; copy the exact current file hash." },
    title: { type: "string", minLength: 1, maxLength: 500 },
    pageKind: { type: "string", minLength: 1, maxLength: 100 },
    content: { type: "string", minLength: 1, description: "Required only for create and replace. It is the complete desired page body." },
    sectionChanges: {
      type: "array",
      minItems: 1,
      maxItems: 20,
      description: "Required only for merge. Upsert complete, fully visible sections or add a new section; Core preserves every other section server-side. Do not select both a parent section and one of its nested child sections in the same patch.",
      items: {
        type: "object",
        required: ["operation", "heading", "content"],
        properties: {
          operation: { const: "upsert_section" },
          heading: { type: "string", minLength: 1, maxLength: 300 },
          level: { type: "integer", minimum: 2, maximum: 6 },
          content: { type: "string", minLength: 1 },
        },
        additionalProperties: false,
      },
    },
    summary: { type: "string", maxLength: 500 },
    domainSchemaId: { type: "string", minLength: 1, maxLength: 200 },
    domainSchemaVersion: { type: "string", minLength: 1, maxLength: 200 },
    domainClassifications: {
      type: "array",
      maxItems: 100,
      items: {
        type: "object",
        required: ["kind", "typeId", "typeName", "schemaMode", "status", "domain", "abe", "be"],
        properties: {
          kind: { type: "string", enum: ["entity", "concept"] },
          typeId: { type: "string", minLength: 1, maxLength: 200 },
          typeName: { type: "string", minLength: 1, maxLength: 500 },
          schemaId: { type: "string", maxLength: 200 },
          schemaVersion: { type: "string", maxLength: 200 },
          schemaMode: { const: "progressive-directory-v2" },
          status: { type: "string", enum: ["classified", "unresolved"] },
          confidence: { type: "number", minimum: 0, maximum: 1 },
          domain: { type: "object" },
          abe: { type: "object" },
          be: { type: "object" },
          resolved: { type: "boolean" },
        },
        additionalProperties: false,
      },
    },
    tags: { type: "array", items: { type: "string", minLength: 1, maxLength: 200 }, maxItems: 100 },
    related: {
      type: "array",
      items: { type: "string", minLength: 1, maxLength: 500 },
      maxItems: 500,
      description: "Canonical Wiki slugs such as entities/customer. Mirror each entry in the body as [[entities/customer]]; do not use wiki/entities/customer.md paths.",
    },
    covers: { type: "array", items: { type: "string", minLength: 1, maxLength: 300 }, maxItems: 1000, description: "page_requirements requirement_id values materialized by this canonical page." },
    sourceRefs: {
      type: "array",
      items: {
        oneOf: [
          analysisSchema.$defs.sourceRef,
          { type: "string", pattern: "^page-[0-9a-f]{20}$" },
        ],
      },
      minItems: 1,
      maxItems: 500,
      description: "Prefer page requirement IDs copied from page_requirement.patch_scaffold. Core resolves them to exact SourceRefs. Complete SourceRef objects remain accepted for backward compatibility.",
    },
    rationale: { type: "string", minLength: 1, maxLength: 10000 },
  },
  allOf: [
    {
      if: { properties: { operation: { enum: ["create", "replace"] } }, required: ["operation"] },
      then: { required: ["content"], not: { required: ["sectionChanges"] } },
    },
    {
      if: { properties: { operation: { const: "merge" } }, required: ["operation"] },
      then: { required: ["sectionChanges"], not: { required: ["content"] } },
    },
  ],
  additionalProperties: false,
})

export const toolSchemas = Object.freeze({ analysisSchema, pagePatchSchema })
